export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const CREATE_PRODUCTS_REQUEST = "CREATE_PRODUCTS_REQUEST";
export const CREATE_PRODUCTS_SUCCESS = "CREATE_PRODUCTS_SUCCESS";
export const CREATE_PRODUCTS_FAILURE = "CREATE_PRODUCTS_FAILURE";

export const GET_TOTAL_PRODUCTS_REQUEST = "GET_TOTAL_PRODUCTS_REQUEST";
export const GET_TOTAL_PRODUCTS_SUCCESS = "GET_TOTAL_PRODUCTS_SUCCESS";
export const GET_TOTAL_PRODUCTS_FAILURE = "GET_TOTAL_PRODUCTS_FAILURE";

export const FILTER_PRODUCTS_REQUEST = "FILTER_PRODUCTS_REQUEST";
export const FILTER_PRODUCTS_SUCCESS = "FILTER_PRODUCTS_SUCCESS";
export const FILTER_PRODUCTS_FAILURE = "FILTER_PRODUCTS_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const IMPORT_PRODUCTS_REQUEST = "IMPORT_PRODUCTS_REQUEST";
export const IMPORT_PRODUCTS_SUCCESS = "IMPORT_PRODUCTS_SUCCESS";
export const IMPORT_PRODUCTS_FAILURE = "IMPORT_PRODUCTS_FAILURE";

export const EXPORT_PRODUCTS_REQUEST = "EXPORT_PRODUCTS_REQUEST";
export const EXPORT_PRODUCTS_SUCCESS = "EXPORT_PRODUCTS_SUCCESS";
export const EXPORT_PRODUCTS_FAILURE = "EXPORT_PRODUCTS_FAILURE";