export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const CREATE_PRODUCTS_REQUEST = "CREATE_PRODUCTS_REQUEST";
export const CREATE_PRODUCTS_SUCCESS = "CREATE_PRODUCTS_SUCCESS";
export const CREATE_PRODUCTS_FAILURE = "CREATE_PRODUCTS_FAILURE";

export const GET_TOTAL_PRODUCTS_REQUEST = "GET_TOTAL_PRODUCTS_REQUEST";
export const GET_TOTAL_PRODUCTS_SUCCESS = "GET_TOTAL_PRODUCTS_SUCCESS";
export const GET_TOTAL_PRODUCTS_FAILURE = "GET_TOTAL_PRODUCTS_FAILURE";